### ISSUE TITLE
Indexing of taxonomy terms triggered too often

### ISSUE THREAD

**Issue by gflcampos** [obiba/mica2#3713]
Looking at the Mica logs, I have noticed that the taxonomy terms are being automatically indexed way too often.
As far as I can tell, it happens every time a request in which the URL starts with `/ws/taxonomy(ies)` or `/ws/variables` is made. This causes the log files to grow in size pretty quickly when using the search page.

This did not happen with Mica 3.3.1. I am using version 3.5.2 right now, but it seems to happen at least since version 3.4.5.
I'm not sure if this behavior is intentional, but just playing around in the search page for a couple of minutes, got a clean `mica.log` up to around 5MB!

**Comment by kazoompa** [comment]
This problem happens when the memory setting for `opal-taxonomy` caching is not large enough. To fix the problem follow these steps:

- download the attached file
- move it to `/etc/mica2`
- edit the file and make sure you increase the value of `maxBytesLocalHeap` as in the example below:
```xml
<cache name="opal-taxonomies"
  maxBytesLocalHeap="50M"
  diskPersistent="true"
  overflowToDisk="true"
  eternal="true">
  <sizeOfPolicy maxDepth="100000"/>
</cache>
```
- make sure the file ownership of the file is correct:
```bash
sudo chown mica:adm /etc/mica2/ehcache.xml
```
- restart Mica service

**Comment by kazoompa** [comment]
Hi,

This problem happens when the memory setting for opal-taxonomy caching is
not large enough. To fix the problem follow these steps:

   - download the attached file
   <https://mail.google.com/mail/u/0?ui=2&ik=0c6aa07177&attid=0.1&permmsgid=msg-a:r7584087947259288083&view=att&disp=safe&realattid=f_jwat2b6x0>
   - move it to /etc/mica2
   - edit the file and make sure you increase the value of maxBytesLocalHeap
   as in the example below:

   <cache name="opal-taxonomies"
     maxBytesLocalHeap="100M"
     diskPersistent="true"
     overflowToDisk="true"
     eternal="true">
     <sizeOfPolicy maxDepth="100000"/></cache>

   - make sure the file ownership of the file is correct:

   sudo chown mica:adm /etc/mica2/ehcache.xml

   - restart Mica service

Best,
Ramin

**Comment by gflcampos** [comment]
Thanks Ramin, that worked!
