### ISSUE TITLE
Website url field

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#3842]
<input type="url">  ?

**Comment by meek0** [comment]
Note that the url field is always transform into a true url on the drupal/portal site.

The problem is that an url that does not start with a protocol will be interpreted (by the browser) to be a `relative` url. Thus an url value of `google.ca` on a portal website `https://portal.website.com` will be interpreted as `https://portal.website.com/google.ca`.

The validation would probably need to be stricter. Else need to find a solution.

**Comment by sofiyad** [comment]
To review
