### ISSUE TITLE
Missing the option to add a study using the mica2 web application

### ISSUE THREAD

**Issue by jottyfan** [obiba/mica2#3968]
**Cannot create a study any longer**
In former versions of the application, I could create a new study simply by using the "add study" button above the list of studies. Even in the demo version of mica2 4.1.0 (https://www.obiba.org/pages/products/mica/), logged in as administrator with all the roles, I cannot find that button. How do I add a new study?

**To Reproduce**
1. Go to 'https://mica-demo.obiba.org/'
2. Login as administrator
3. open the studies page
4. try to add a study

**Expected behavior**
There should be a button that allows me to add new studies, and that button should be available easily.

**Screenshots**
the old button:
![image](https://user-images.githubusercontent.com/13251275/87325051-40d52000-c531-11ea-813b-57c417f548fa.png)
the new page without the add study button:
![image](https://user-images.githubusercontent.com/13251275/87325136-5ba79480-c531-11ea-98a7-5e159950ede4.png)

**Additional context**
Also, I could not find a documentation how to add studies in general. There is no handbook, the documentation of http://micadoc.obiba.org/en/latest/ as like as http://micadoc.obiba.org/en/latest/web-user-guide/index.html is useless for the end user. Maybe you could at least provide a few quick howto tutorials to help the end user to work with that software?

**Comment by ymarcon** [comment]
You are mixing the public pages (published content) and the administration pages (draft content). Click on the lock icon on the right of footer to access to the administration content. For instance go to https://mica-demo.obiba.org/admin

Mica 4.x is a major release which introduced the public pages, see [Mica 4.0 release notes](https://www.obiba.org/pages/news/release/mica2/4.0/), since then the default landing page is not the content administration app.

**Comment by ymarcon** [comment]
As a side note, a "Administration" menu will be added in the top toolbar, only visible for users having appropriate permissions.
