### ISSUE TITLE
Mica Search - Suggestion in the listing pages does not handle special characters

### ISSUE THREAD

**Issue by kazoompa** [obiba/mica2#4017]
To prevent issues related to the client RQL parser some character such as `:` is removed from the search query causing results as seen below. 

Possible resolutions:
- special tokenizers
- split string on these special char's and create AND queries under the hood

To be investigated...

![image](https://user-images.githubusercontent.com/2814716/93923329-3da0a200-fce1-11ea-929f-e83ddafcd7c0.png)

**Comment by meek0** [comment]
The suggested field's cleanup needs a review.  What is done [here](https://github.com/obiba/mica2/blob/master/mica-search/src/main/java/org/obiba/mica/search/AbstractDocumentService.java#L131-L146) and  [here](https://github.com/obiba/mica-search-es/blob/master/src/main/java/org/obiba/es/mica/ESSearcher.java#L283-L287) (same place/thing in mica-search-es7) are not appropriate: the cleanup might give a suggestion that will never give a response.

Id's should be a sure thing (needs testing) but phrases are not always correct due to the need to escape or remove some characters.

Splitting the phrases on lucene special characters and the joining them by an `AND` seems to give the best result (after removing most of the cleanups that are before).
