### ISSUE TITLE
bug in filtering on the website (hiding domains, studies with value 0)

### ISSUE THREAD

**Issue by sofiyad** [obiba/mica2#4046]

**Comment by meek0** [comment]
This might not be a filtering issue but rather a search issue: I get errors with [this query](https://mica-staging.maelstrom-research.org/admin#/search?display=coverage&withZeros=false&query=variable(or(exists(Mlstr_habits.Alcohol),exists(Mlstr_habits.Nutrition))),study(in(Mica_study.id,(abc)))) even before "filtering", while [this one](https://mica-staging.maelstrom-research.org/admin#/search?display=coverage&withZeros=false&query=variable(or(exists(Mlstr_area.Sociodemographic_economic_characteristics),exists(Mlstr_area.Lifestyle_behaviours))),study(in(Mica_study.id,(apron)))) works well with and without the "filtering".

Note that the one that fails is done with "scales" while the other is done with "areas". Because of that, I can't seem to be able to reproduce it locally. Needs further investigation.
