### ISSUE TITLE
DAR/amendment/feasibility forms versioning

### ISSUE THREAD

**Issue by tdemalliard** [obiba/mica2#4208]
**Is your feature request related to a problem? Please describe.**
As we improve our data access system, we would like to reflect it in our forms and preserve the compatibility with previous DAR.

**Describe the solution you'd like**
Versioning with forms. A DAR would be bound to a specific version. DAR versions could be accessed via admin interface. I think only the last version should be modifiable.

**Describe alternatives you've considered**
Using javascript, css and class to show or hide par of the forms.

**Additional context**
None

**Comment by ymarcon** [comment]
That is a nice feature, as it makes the DAR system more viable in the long term. Probably the link between a DAR and a version number of the form should be established only when the DAR state is finalized (approved/rejected), otherwise bug fixes in the form would not apply to a currently processed DAR. I guess that you expect this feature to feasibility, main and amendment forms.

To do:
* extend usage of the `GitService` to the DAR forms: versions of forms are persisted in mica's git
* link a DAR instance to a form version (commit ID) on finalization (approval/rejection)
* update DAR pages display accordingly (fetch appropriate form version to render)
* add upgrade task to initialize DAR forms git repos and link finalized DARs with latest form version.

5 days of dev.

**Comment by tdemalliard** [comment]
Hi Yannick. I would like to add some thought to this :
1. Should we include versioning with translation ? 
I think that we are ok without versioning, provided that we add new variables names and not re-use current variables
2. Should the versioning be set at submission time? And could it be flexible, like reset the last version or set by hand if needed for current access requests?
We are not sure if the version should not be set as the researcher submit its form : for a DAR, there could be 2 months between the submission and the approbation and there. Maybe for the 2nd question, this could be achieve through the mongo DB.

**Comment by ymarcon** [comment]
1. translations are defined globally then not including these in the versioning would be easier. As you said, use new translation keys for new text.
2. yes, you are right, linking to a form version at submission time would be better as the form data are not supposed to be modified afterwards. In case of severe issue, administrator could set to latest version (intermediate versions could be problematic as it means that one is aware of the revision history and can compare etc., i.e. a lot of ui changes for minor benefit)
